# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddaf58bda0a5991d5208673c82affe5d6d81c6435e99caa2ccd414b6aa9bbef405c9bdeac0e483f4d0a5bb65710bf868491a3d616d5a83096b771a8880ae5646

test:
  secret_key_base: 1590baad9556102a0c2a333aaed83a94607b0bd5a191c423e8b2a877a1d9770a950e2080ed51d7e175223ec0ab807f321c6697c052b9b4d3a5eb0ae9cf7ae28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
